INSERT INTO task_files (task_id, file)
                 VALUES ('1', 'Robby_project_1.pdf');INSERT INTO task_files (task_id, file)
                 VALUES ('2', 'john_project_2.pdf');INSERT INTO task_files (task_id, file)
                 VALUES ('3', 'Adel_project_3.pdf');INSERT INTO task_files (task_id, file)
                 VALUES ('4', 'Sara_project_4.pdf');INSERT INTO task_files (task_id, file)
                 VALUES ('5', 'john_project_2-1.pdf');INSERT INTO task_files (task_id, file)
                 VALUES ('6', 'Robby_project_1-1.pdf');INSERT INTO task_files (task_id, file)
                 VALUES ('7', 'Robby_project_1.pdf');INSERT INTO task_files (task_id, file)
                 VALUES ('8', 'john_project_2.pdf');INSERT INTO task_files (task_id, file)
                 VALUES ('9', 'Adel_project_3.doc');INSERT INTO task_files (task_id, file)
                 VALUES ('10', 'Sara_project_4.doc');INSERT INTO task_files (task_id, file)
                 VALUES ('9', 'john_project_2-1.doc');INSERT INTO task_files (task_id, file)
                 VALUES ('8', 'Robby_project_1-1.doc');INSERT INTO task_files (task_id, file)
                 VALUES ('7', 'Robby_project_1-1.doc');INSERT INTO task_files (task_id, file)
                 VALUES ('1', 'Robby_project_1.psd');INSERT INTO task_files (task_id, file)
                 VALUES ('2', 'john_project_2.psd');INSERT INTO task_files (task_id, file)
                 VALUES ('3', 'Adel_project_3.psd');INSERT INTO task_files (task_id, file)
                 VALUES ('4', 'Sara_project_4.psd');INSERT INTO task_files (task_id, file)
                 VALUES ('5', 'john_project_2-1.psd');INSERT INTO task_files (task_id, file)
                 VALUES ('6', 'Robby_project_1-1.psd');