INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('1', '4');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('2', '3');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('3', '2');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('5', '1');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('6', '8');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('7', '6');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('8', '4');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('9', '3');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('10', '2');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('11', '1');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('12', '8');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('1', '6');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('2', '4');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('3', '3');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('4', '2');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('5', '7');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('6', '4');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('7', '5');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('19', '1');INSERT INTO user_specializations (user_id, category_id)
                 VALUES ('20', '3');