INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('1', '11', '1');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('2', '12', '1');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('3', '13', '0');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('4', '14', '0');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('5', '15', '0');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('6', '16', '1');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('7', '17', '1');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('8', '18', '0');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('9', '19', '1');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('10', '20', '1');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('1', '20', '1');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('2', '19', '1');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('3', '18', '0');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('4', '17', '0');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('5', '16', '0');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('6', '11', '1');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('7', '12', '1');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('8', '13', '0');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('9', '14', '1');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('10', '15', '1');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('1', '15', '1');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('2', '14', '1');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('3', '13', '0');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('4', '12', '0');INSERT INTO user_favorites (user_id, favorite_id, on_off)
                 VALUES ('5', '11', '0');