INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('1', '11', 'I best Piano mover');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('2', '12', 'We will do everything without noise and dust');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('3', '13', 'I am grut');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('4', '14', 'Can do it one month');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('5', '15', ' gkeik lvllep nale lnlks lne');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('6', '16', 'I best Piano mover');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('7', '17', 'We will do everything without noise and dust');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('8', '18', 'I am grut');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('9', '19', 'Can do it one month');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('10', '20', ' gkeik lvllep nale lnlks lne');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('1', '11', 'I best Piano mover');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('2', '12', 'We will do everything without noise and dust');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('3', '13', 'I am grut');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('4', '14', 'Can do it one month');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('5', '15', ' gkeik lvllep nale lnlks lne');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('1', '16', 'I best Piano mover');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('2', '17', 'We will do everything without noise and dust');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('3', '18', 'I am grut');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('4', '19', 'Can do it one month');INSERT INTO offers (id_task, id_contractor, desk)
                 VALUES ('5', '20', ' gkeik lvllep nale lnlks lne');